In [0]:
# !wget https://fmi-unibuc-ia.github.io/ia/Data/data_lab5.zip

--2020-05-06 07:05:18--  https://fmi-unibuc-ia.github.io/ia/Data/data_lab5.zip
Resolving fmi-unibuc-ia.github.io (fmi-unibuc-ia.github.io)... 185.199.109.153, 185.199.108.153, 185.199.110.153, ...
Connecting to fmi-unibuc-ia.github.io (fmi-unibuc-ia.github.io)|185.199.109.153|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 503740 (492K) [application/zip]
Saving to: ‘data_lab5.zip’

data_lab5.zip       100%[===================>] 491.93K  --.-KB/s    in 0.08s   

2020-05-06 07:05:20 (5.95 MB/s) - ‘data_lab5.zip’ saved [503740/503740]



In [0]:
# !unzip data_lab5.zip

Archive:  data_lab5.zip
  inflating: data/test_labels.npy    
  inflating: data/test_sentences.npy  
  inflating: data/training_labels.npy  
  inflating: data/training_sentences.npy  


In [1]:
import numpy as np

In [5]:
train_data = np.load('data-lab5/training_sentences.npy', allow_pickle=True)
train_labels    = np.load('data-lab5/training_labels.npy', allow_pickle=True).astype(np.bool)
test_data  = np.load('data-lab5/test_sentences.npy', allow_pickle=True)
test_labels     = np.load('data-lab5/test_labels.npy', allow_pickle=True).astype(np.bool)

In [6]:
train_data[0]

['Probably', 'not', 'still', 'going', 'over', 'some', 'stuff', 'here']

In [7]:
train_data[:10]

array([list(['Probably', 'not', 'still', 'going', 'over', 'some', 'stuff', 'here']),
       list(['I', 'HAVE', 'A', 'DATE', 'ON', 'SUNDAY', 'WITH', 'WILL']),
       list(['Thanks', '4', 'your', 'continued', 'support', 'Your', 'question', 'this', 'week', 'will', 'enter', 'u', 'in2', 'our', 'draw', '4', '£100', 'cash', 'Name', 'the', 'NEW', 'US', 'President', 'txt', 'ans', 'to', '80082']),
       list(['Dear', '0776xxxxxxx', 'Uve', 'been', 'invited', 'to', 'XCHAT', 'This', 'is', 'our', 'final', 'attempt', 'to', 'contact', 'u', 'Txt', 'CHAT', 'to', '86688', '150pMsgrcvdHGSuite3422LandsRowW1J6HL', 'LDN', '18yrs']),
       list(['I', 'sent', 'my', 'scores', 'to', 'sophas', 'and', 'i', 'had', 'to', 'do', 'secondary', 'application', 'for', 'a', 'few', 'schools', 'I', 'think', 'if', 'you', 'are', 'thinking', 'of', 'applying', 'do', 'a', 'research', 'on', 'cost', 'also', 'Contact', 'joke', 'ogunrinde', 'her', 'school', 'is', 'one', 'me', 'the', 'less', 'expensive', 'ones']),
       list(['Koth

In [8]:
len(train_data)

3734

In [9]:
from sklearn import preprocessing

def normalize_data(train_data, test_data, type=None):
    scaler = None
    if type == 'standard':
        scaler = preprocessing.StandardScaler()

    elif type == 'min_max':
        scaler = preprocessing.MinMaxScaler()

    elif type == 'l1' or type == 'l2':
        scaler = preprocessing.Normalizer(norm=type)

    if scaler is not None:
        scaler.fit(train_data)
        scaled_train_data = scaler.transform(train_data)
        scaled_test_data = scaler.transform(test_data)
        return scaled_train_data, scaled_test_data
    else:
        return train_data, test_data

In [10]:
class BagOfWords:

    def __init__(self):
        self.vocab = {} # dictionar cuvant -> idx
        self.words = [] # lista de cuvinte

    def build_vocabulary(self, train_data):
        for sentence in train_data:
            for word in sentence:
                if word not in self.vocab:
                    self.vocab[word] = len(self.words)
                    self.words.append(word)
        return len(self.words)

    def get_features(self, data):
        result = np.zeros((data.shape[0], len(self.words))) # 3734x9522
        for idx, sentence in enumerate(data):
            for word in sentence:
                if word in self.vocab:
                    result[idx, self.vocab[word]] += 1
        return result

In [11]:
bow = BagOfWords()
print(bow.build_vocabulary(train_data))

9522


In [12]:
train_features = bow.get_features(train_data)

print(train_features.shape)
print(train_features)

(3734, 9522)
[[1. 1. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]]


In [13]:
print(train_data[0])
print(train_features[0][:20])

['Probably', 'not', 'still', 'going', 'over', 'some', 'stuff', 'here']
[1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [14]:
print([(x, bow.vocab[x]) for x in train_data[102]])

[('Babe', 799), ('U', 168), ('want', 800), ('me', 90), ('dont', 247), ('u', 27), ('baby', 801), ('Im', 334), ('nasty', 802), ('and', 63), ('have', 471), ('a', 70), ('thing', 482), ('4', 17), ('filthyguys', 803), ('Fancy', 804), ('a', 70), ('rude', 805), ('time', 145), ('with', 195), ('a', 70), ('sexy', 806), ('bitch', 807), ('How', 414), ('about', 189), ('we', 268), ('go', 307), ('slo', 808), ('n', 542), ('hard', 809), ('Txt', 53), ('XXX', 810), ('SLO4msgs', 811)]


In [15]:
test_features = bow.get_features(test_data)

print(test_features.shape)
print(test_features)

(1840, 9522)
[[0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [16]:
norm_train_features, norm_test_features = normalize_data(train_features, test_features, 'l2')

In [17]:
norm_train_features

array([[0.35355339, 0.35355339, 0.35355339, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.19611614, 0.19611614,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.33333333],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [18]:
norm_test_features

array([[0. , 0. , 0.5, ..., 0. , 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 0. ],
       ...,
       [0. , 0. , 0. , ..., 0. , 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 0. ]])

In [19]:
# !wget https://fmi-unibuc-ia.github.io/ia/Data/Lab%205%20-%20toy%20example%20-%20SVM.zip

'wget' is not recognized as an internal or external command,
operable program or batch file.


In [0]:
# !unzip 'Lab 5 - toy example - SVM.zip'

Archive:  Lab 5 - toy example - SVM.zip
  inflating: data/svm_train_data.npy  
  inflating: data/svm_train_labels.npy  
  inflating: Lab 5 - toy example - SVM.ipynb  


In [20]:
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

svm_train_data   = np.load('data-lab5/svm_train_data.npy', allow_pickle=True)
svm_train_labels = np.load('data-lab5/svm_train_labels.npy', allow_pickle=True).astype(np.bool)

X_train, X_valid, y_train, y_valid = train_test_split(svm_train_data, svm_train_labels, test_size=0.2)

In [21]:
svc = SVC(1, 'linear')
svc.fit(X_train, y_train)
svc.score(X_valid, y_valid)

1.0

In [28]:
# 6.
from sklearn import svm
for C in [0.1, 0.3, 0.7]:
    model = svm.SVC(C=C, kernel='linear')
    model.fit(norm_train_features, train_labels)

    #  Calculați acuratețea și F1-score pentrumulțimea de testare

    from sklearn.metrics import accuracy_score, f1_score, classification_report

    test_preds = model.predict(norm_test_features)
    print(accuracy_score(test_labels, test_preds))
    print(f1_score(test_labels, test_preds))
    print(classification_report(test_labels, test_preds))

0.9168478260869565
0.5714285714285715
              precision    recall  f1-score   support

       False       0.91      1.00      0.95      1585
        True       1.00      0.40      0.57       255

    accuracy                           0.92      1840
   macro avg       0.96      0.70      0.76      1840
weighted avg       0.92      0.92      0.90      1840

0.9739130434782609
0.8965517241379309
              precision    recall  f1-score   support

       False       0.97      1.00      0.99      1585
        True       1.00      0.82      0.90       255

    accuracy                           0.97      1840
   macro avg       0.98      0.91      0.94      1840
weighted avg       0.97      0.97      0.97      1840

0.9809782608695652
0.9284253578732106
              precision    recall  f1-score   support

       False       0.98      1.00      0.99      1585
        True       0.97      0.89      0.93       255

    accuracy                           0.98      1840
   macro avg  

In [27]:
weights = np.squeeze(model.coef_)
indexes = np.argsort(weights)
words = np.array(bow.words)
print('NEGATIVE', words[indexes[-10:]]) # Spam words
print('POSITIVE', words[indexes[:10]]) # Good words

NEGATIVE ['Text' 'To' 'mobile' 'CALL' 'FREE' 'txt' '&' 'Call' 'Txt' 'STOP']
POSITIVE ['&lt#&gt' 'me' 'i' 'Going' 'him' 'Ok' 'I' 'Ill' 'my' 'Im']


array([-0.0120314 , -0.11716947, -0.63366342, ...,  0.        ,
        0.        ,  0.        ])