In [3]:
import numpy as np
from sklearn.utils import shuffle
# load training data
training_data = np.load('data-lab6/training_data.npy')
prices = np.load('data-lab6/prices.npy')
# print the first 4 samples
print('The first 4 samples are:\n ', training_data[:4])
print('The first 4 prices are:\n ', prices[:4])
# shuffle
training_data, prices = shuffle(training_data, prices, random_state=0)

The first 4 samples are:
  [[2.0150e+03 4.1000e+04 1.9670e+01 1.5820e+03 1.2620e+02 5.0000e+00
  1.0000e+00 0.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00
  1.0000e+00 0.0000e+00]
 [2.0110e+03 4.6000e+04 1.8200e+01 1.1990e+03 8.8700e+01 5.0000e+00
  1.0000e+00 0.0000e+00 0.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  1.0000e+00 0.0000e+00]
 [2.0120e+03 8.7000e+04 2.0770e+01 1.2480e+03 8.8760e+01 7.0000e+00
  1.0000e+00 0.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00
  1.0000e+00 0.0000e+00]
 [2.0130e+03 8.6999e+04 2.3080e+01 1.4610e+03 6.3100e+01 5.0000e+00
  1.0000e+00 0.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00
  1.0000e+00 0.0000e+00]]
The first 4 prices are:
  [12.5  4.5  6.   3.5]


In [1]:
from sklearn.preprocessing import MinMaxScaler

In [6]:
scaler = MinMaxScaler()
transData = np.transpose(training_data)
scaler.fit(transData)
training_data_processed = np.transpose(scaler.transform (transData))
training_data_processed

array([[1.0991227e-01, 1.0000000e+00, 1.1933955e-03, ..., 0.0000000e+00,
        0.0000000e+00, 5.4492943e-05],
       [2.2142857e-02, 9.9999994e-01, 2.3186814e-04, ..., 0.0000000e+00,
        1.0989011e-05, 0.0000000e+00],
       [9.7643584e-02, 1.0000000e+00, 9.1450132e-04, ..., 0.0000000e+00,
        0.0000000e+00, 4.8386315e-05],
       ...,
       [3.5710476e-02, 1.0000000e+00, 3.1122178e-04, ..., 0.0000000e+00,
        1.7784101e-05, 0.0000000e+00],
       [3.3550002e-02, 1.0000000e+00, 3.2733331e-04, ..., 0.0000000e+00,
        1.6666667e-05, 0.0000000e+00],
       [2.8757143e-01, 1.0000000e+00, 2.5671427e-03, ..., 0.0000000e+00,
        0.0000000e+00, 1.4285714e-04]], dtype=float32)

In [21]:
scaler = MinMaxScaler()
price_to_scale = np.array(prices)
price_to_scale = price_to_scale.reshape((1,-1))
scaler.fit(price_to_scale)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [22]:
prices_processed = scaler.transform (price_to_scale)
prices_processed

array([[0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [19]:
prices

array([3.41, 2.5 , 7.55, ..., 2.4 , 7.5 , 3.65], dtype=float32)